### ISSUE TITLE
Logged data is lost on power cycle

### ISSUE THREAD

**Issue by Pete-in-Perth** [vitotai/BrewPiLess#370] opened 2022-08-04 05:32 UTC
Hi. I've just upgraded to BPL 4.2 (was something like 3.2 previously). I often use the data logging function. In the new version, it appears data is lost after a power cycle.
I'm using a Wemos D1 Mini board with Thorax configuration.
Have attached a screenshot.
Any suggestions?

![Screenshot 2022-08-04 133100](https://user-images.githubusercontent.com/30366062/182770006-dc1e3542-966a-4e3c-90df-f6325d59caa9.png)
.

**Comment by vitotai** [comment] 2022-08-07 01:01
There is a new option, "Write on Buffer", which should be NO/FALSE/DISABLED to encourage writing whenever there is new data.

![logging](https://user-images.githubusercontent.com/15953213/183270716-4bbd910a-30e1-4bb7-bee1-8ced070effd8.jpg)

**Comment by Pete-in-Perth** [comment] 2022-08-16 00:03
Thanks for your reply. I've played around with the "Write on Buffer Full" setting. 

With it turned on, the log is lost completely on a power cycle, and a new log needs to be started.

With it turned off, the log appears to be there but there is no data showing from before the power cycle (as per the screenshot on my first post).

Thanks!

**Comment by vitotai** [comment] 2022-08-26 13:58
I tried it on my testing platform, an ESP32, but I couldn't reproduce it.
However, something strange happened on my working setup in my last brew. The log stop like someone stop it while I didn't remember doing so. I am still hurting this issue.

**Comment by Adilson6060** [comment] 2022-09-06 23:45
It is the same with me . It was right , but I don’t known why brewpiless font show the fermentation begin #
![B25393FC-3063-41FF-9381-1B3F758FB2D6](https://user-images.githubusercontent.com/22159216/188758793-d1879afd-7d5a-46f8-ae4a-bfb061be7413.png)

**Comment by dumpamob** [comment] 2022-09-26 01:19
It happened here too, if you turn off the power, the graph disappears in the interface and also in the log when viewed by the Log Viewer.

**Comment by bandaxadibar** [comment] 2023-02-01 12:36
I confirm the feedbacks informed by the other people. Yesterday, all the data disapear.

**Comment by gumazza** [comment] 2023-02-18 09:46
I'm using the latest version (4.2rc4) and the problem still persists, here after 5 days the LOG disappears.
![BPL](https://user-images.githubusercontent.com/44449407/219853678-3212fbce-4a73-464a-b59e-0428633cb5f3.jpg)

**Comment by ksga** [comment] 2023-05-10 08:39
Running on Wemos D1 Mini's, and had the same issue with logs being lost on power cycles.
Grabbed the source this morning, made the same changes as @havardAasen committed, and can confirm that it appears to work:
![image](https://github.com/vitotai/BrewPiLess/assets/546026/f7f661e9-762c-43e2-8f20-67dc1ee09797)

**Comment by danestead** [comment] 2024-01-09 23:58
I'm having this same issue, though I'm on version 4.3.

I've looked at havardAasen's edit to brewlogger.cpp but the source looks the same, so I haven't made any changes.

Anyone else having this problem and able to provide a solution?

**Comment by danestead** [comment] 2024-01-10 00:12
> Thanks for your reply. I've played around with the "Write on Buffer Full" setting.
> 
> With it turned on, the log is lost completely on a power cycle, and a new log needs to be started.
> 
> With it turned off, the log appears to be there but there is no data showing from before the power cycle (as per the screenshot on my first post).
> 
> Thanks!

Hi Pete, I'm also in Perth. Did you manage to fix this?

**Comment by danestead** [comment] 2024-01-10 00:13
> Running on Wemos D1 Mini's, and had the same issue with logs being lost on power cycles. Grabbed the source this morning, made the same changes as @havardAasen committed, and can confirm that it appears to work: ![image](https://private-user-images.githubusercontent.com/546026/237329836-f7f661e9-762c-43e2-8f20-67dc1ee09797.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NDU2MTcsIm5iZiI6MTcwNDg0NTMxNywicGF0aCI6Ii81NDYwMjYvMjM3MzI5ODM2LWY3ZjY2MWU5LTc2MmMtNDNlMi04ZjIwLTY3ZGMxZWUwOTc5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMFQwMDA4MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODVlYTQ0M2EzZDcxZTExYWEyYmE1MGNkYmRiNzFhODM1Yzc3MGU5ZTIxYTAyMWE4YjEzN2JjYzVmYTQyNjVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6meMLF5mvq2HUr1nXFLi2dZyrPwTdYBPVBQ65AtDMns)

Is this still working for you?

Regarding the change to brewlogger.cpp, did you manually type in the changes or download the whole file and replace?

**Comment by dumpamob** [comment] 2024-01-11 19:15
here with 4.3.1, D1 Mini, and making the changes suggested by the @havardAasen. solved. 
I deleted the lines that the @havardAasen marked, saved, build and upload.

**Comment by danestead** [comment] 2024-01-11 22:01
> here with 4.3.1, D1 Mini, and making the changes suggested by the @havardAasen. solved. I deleted the lines that the @havardAasen marked, saved, build and upload.

Ah, so delete the lines shaded pink/red?

**Comment by dumpamob** [comment] 2024-01-11 22:17
> > here with 4.3.1, D1 Mini, and making the changes suggested by the @havardAasen. solved. I deleted the lines that the @havardAasen marked, saved, build and upload.
> 
> Ah, so delete the lines shaded pink/red?

Yes that's right.

**Closed** 2024-01-16 01:50 UTC
