### ISSUE TITLE
Beer Profiles are broken in v4.2p3

### ISSUE THREAD

**Issue by alexlark** [vitotai/BrewPiLess#363] opened 2022-04-07 09:58 UTC
Issue: Saved beer profiles are truncated and hyperlinks broken in v4.2p3

To replicate issue: Create a beer profile and save it, navigate away from the beer profiles, navigate back to beer profiles and load a beer profile. The saved profiles will be truncated and hyperlinks broken.

Issue does not exist in v4.1r4

**Comment by vitotai** [comment] 2022-04-07 14:10
I just push a new version, modified layout. Try if it works for you.

**Comment by alexlark** [comment] 2022-04-07 16:36
I can see the new DEL buttons, and they work, but the profile names are still truncated and do not work :-/

![image](https://user-images.githubusercontent.com/36233719/162253305-391aafd0-af60-4712-b440-0293aaaef7c9.png)

**Comment by vitotai** [comment] 2022-04-08 03:12
what browers are you using?

![profile](https://user-images.githubusercontent.com/15953213/162355639-68fd0e96-5a3b-4c07-89ac-79d00798d2a7.jpg)
![IMG_4035](https://user-images.githubusercontent.com/15953213/162355647-8628291b-6f90-4043-bb8a-d88ac5d46111.PNG)

**Comment by alexlark** [comment] 2022-04-08 08:42
I'm using Chrome and I tried in Edge as well.

The profiles save and I can click them but once I navigate away from the page, and back, they are then truncated. Also, my profiles do not have a a forward slash prefix and when I navigate to http://brewpiless.local:8008/filemanager I am unable to see them saved.

The DEL button removes them but when navigating away, and back, they re-appear.

Version v4.1r4 is OK

![image](https://user-images.githubusercontent.com/36233719/162399365-d963f789-d443-430f-b653-08a50b3f0d2b.png)

**Comment by vitotai** [comment] 2022-04-09 01:17
I didn't change anything about control panel or profiles after 4.1. In fact, I totally forget profile loading/saving. There was a delete buttons in classic UI, but it didn't show up in new UI. It was until you mentioned that I just knew that. 

What on my Mac with Chrome:
![截圖 2022-04-09 上午9 12 32](https://user-images.githubusercontent.com/15953213/162550887-0bc3725b-627e-4e37-966f-09a7cb654039.jpg)

**Comment by vitotai** [comment] 2022-04-09 01:26
It's difficult for me to solve issues if I couldn't reproduce by myself. However, if you can provide more information, I might be able to give it a try.
On Chrome, select "View"->"Development Option"->"Javascript Console".
Click the icon marked as "1" in the following picture. Click on around "DEL" button. then Click "Computed" marked as "2". Capture the screen and show it to me.
![截圖 2022-04-09 上午9 19 55](https://user-images.githubusercontent.com/15953213/162551152-7531d47d-d31a-40d6-a431-a4a99e92a11f.jpg)

**Comment by alexlark** [comment] 2022-04-09 12:57
This has got to be linked to the way the list of profiles are fetched. The list of profiles are being cut by 2 characters so all further GET /POST requests are using the wrong URL....

![image](https://user-images.githubusercontent.com/36233719/162575026-a8ee16f3-2bff-437c-a150-6a760d59f3c2.png)


But the profiles are actually getting saved in the correct location....

![image](https://user-images.githubusercontent.com/36233719/162575056-5579057f-2582-4f51-b5bd-e4225b948fad.png)

**Comment by vitotai** [comment] 2022-04-10 03:28
Yeah. You are right. 
I'm converting to LittleFS and didn't notice the different behaviors between LittleFS and SPIFFS.
Just push a new commit. 
Sorry about that.

**Comment by alexlark** [comment] 2022-04-10 09:11
All working now, thanks. Loading and deleting work as expected.

Just a minor observation, when viewing the filemanager the profiles folder does not expand whereas the logs folder does. Just pointing this out if this was unintended or helps with the LittleFS conversion...

![image](https://user-images.githubusercontent.com/36233719/162611175-55d194ad-9978-46bb-9c36-f4478c2ee222.png)

**Closed** 2022-04-22 09:34 UTC
